pipelines:
  branches:
    'dev':
    - step:
        name: Dotnet Build / Build Docker Image
        image: mcr.microsoft.com/dotnet/core/sdk:2.2
        caches:
          - dotnetcore
        script:
          - export IMAGE_NAME=$DOCKER_REPO/$IMAGE_PROJECT_TYPE-$IMAGE_COMPONENT_NAME:$BITBUCKET_BRANCH
          - /bin/bash ./build-scripts/version-update.sh 1.0.$BITBUCKET_BUILD_NUMBER
          - dotnet build $PROJECT_NAME.sln --configuration Release
          - dotnet test $PROJECT_NAME.sln --no-restore --configuration Release
          - dotnet publish src/$PROJECT_NAME/$PROJECT_NAME.csproj --no-restore --configuration Release --output ../../publish
          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build -t $IMAGE_NAME ./publish
          # authenticate with the Docker Hub registry
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          # push the new Docker image to the Docker registry
          - docker push $IMAGE_NAME
        services:
          - docker
    - step:
          # trigger: manual
          name: Deploy to Kubernetes
          image: atlassian/pipelines-kubectl
          script:
          - echo $Dev_Kube_Token | base64 -d > ./kube_token
          - echo $Dev_Kube_CA | base64 -d > ./kube_ca
          - kubectl config set-cluster maven-demo-aks --server=https://maven-demo-aks-b54a5075.hcp.westeurope.azmk8s.io:443 --certificate-authority="./kube_ca"
          - kubectl config set-credentials gitlab-user --token="$(cat ./kube_token)"
          - kubectl config set-context maven-demo-aks --cluster=maven-demo-aks --user=gitlab-user
          - kubectl config use-context maven-demo-aks
          # Change Yamls
          - export CPApiKey_Encoded=$(echo -n $CPApi_Key | base64)
          - sed -i -e "s|\$version|$BITBUCKET_BUILD_NUMBER|"  deploy-yamls/deployment.yaml
          - sed -i -e "s|\$ConnectionString|$SETTINGS_URL|"  deploy-yamls/deployment.yaml
          - sed -i -e "s|\$CPApiKey|$CPApiKey_Encoded|"  deploy-yamls/secret.yaml
          - cat deploy-yamls/deployment.yaml
          # Apply Yaml Files
          - kubectl apply -f  deploy-yamls/namespace.yaml
          - kubectl apply -f  deploy-yamls/secret.yaml
          - kubectl apply -f  deploy-yamls/service.yaml
          - kubectl apply -f  deploy-yamls/deployment.yaml

    'master':
    - step:
        name: Dotnet Build / Build Docker Image
        image: mcr.microsoft.com/dotnet/core/sdk:2.2
        caches:
          - dotnetcore
        script:
          - export IMAGE_NAME=$DOCKER_REPO/$IMAGE_PROJECT_TYPE-$IMAGE_COMPONENT_NAME:$BITBUCKET_BRANCH
          - /bin/bash ./build-scripts/version-update.sh 1.0.$BITBUCKET_BUILD_NUMBER
          - dotnet build $PROJECT_NAME.sln --configuration Release
          - dotnet test $PROJECT_NAME.sln --no-restore --configuration Release
          - dotnet publish src/$PROJECT_NAME/$PROJECT_NAME.csproj --no-restore --configuration Release --output ../../publish
          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build -t $IMAGE_NAME ./publish
          # authenticate with the Docker Hub registry
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          # push the new Docker image to the Docker registry
          - docker push $IMAGE_NAME
        services:
          - docker
